### ISSUE TITLE
怎么自定义修正论坛兼容？

### ISSUE THREAD

**Issue by lshilshi** [bmqy/bbs_quickreply#17]
小白，看了下代码，发现无处下手

飞客网，https://www.flyert.com/forum.php?mod=forumdisplay&orderby=dateline&sum=226&fid=226
在回复/快速回复界面

可以出现“快捷回帖”前缀+下拉回复框+设置按钮
但是下拉回复框 内容空白
最后的 AI回复按钮 不显示

遇到类似问题，如何自定义增加修正，可以来个简单示例吗？

谢谢大作！

**Comment by bmqy** [comment]
貌似是没有了明显的论坛特征标识，导致脚本bug了

**Comment by bmqy** [comment]
可以更新新版试试
